Feature: Calculation of the next generation of Conway's game of life

    Scenario: Any live cell with fewer than two live neighbours dies, as if caused by underpopulation.
        When the current cells' generation is the following:
        """
        4 8
        ........
        ..*.....
        ..*.*...
        ........
        """
        Then the next generation should be:
        """
        4 8
        ........
        ........
        ........
        ........
        """

    Scenario: Any live cell with more than three live neighbours dies, as if by overcrowding.
        When the current cells' generation is the following:
        """
        4 8
        ........
        ...**...
        ...**...
        ....*...
        """
        Then the next generation should be:
        """
        4 8
        ........
        ...**...
        ........
        ....*...
        """

    Scenario: Any live cell with two or three live neighbours lives on to the next generation.
        When the current cells' generation is the following:
        """
        4 8
        ....*...
        ...**...
        ....*...
        ........
        """
        Then the next generation should be:
        """
        4 8
        ....*...
        ...**...
        ....*...
        ........
        """

    Scenario: Any dead cell with exactly three live neighbours becomes a live cell.
        When the current cells' generation is the following:
        """
        4 8
        ........
        ....*...
        ...**...
        ........
        """
        Then the next generation should be:
        """
        4 8
        ........
        ...**...
        ...**...
        ........
        """
